# Path to your oh-my-zsh installation.
export ZSH=/home/piontec/.oh-my-zsh

export WORKON_HOME=$HOME/.virtualenvs

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="risto"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(aws common-aliases debian dirhistory docker docker-compose git git-flow git-hubflow httpie kubectl pass sudo systemd virtualenvwrapper terraform)

# User configuration
export GOPATH=~/devel/go
export GOROOT=/usr/lib/go-1.12

export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/bin/:$GOROOT/bin:$GOPATH/bin"
# export MANPATH="/usr/local/man:$MANPATH"
export TF_PLUGIN_CACHE_DIR=/opt/terraform-plugin-dir

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# work aliases
if [[ $HOST == "central-ansible" || $HOST == "central-ansible-test" || $HOST == "cow" ]]; then
  KUBE_HELPER_SETUP_PRIVATE=1
  cd ~/central-kubernetes/; source ./set_team_env.sh; cd ~
fi

if [[ $HOST == "central-ansible" || $HOST == "central-ansible-test" ]]; then
  cd ~/central-kubernetes/; source ./set_pass_env.sh
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias tf=terraform
unalias cp
unalias rm
list_containers() {docker -H $1 ps --format 'table{{.Names}}\t{{ .Label "com.trilogy.company"}}\t{{ .Label "com.trilogy.product"}}\t{{ .Label "com.trilogy.service"}}\t{{ .Label "com.trilogy.stage"}}\t{{ .Label "com.trilogy.team"}}\t{{ .Label "com.trilogy.maintainer.email"}}\t{{ .Label "com.trilogy.maintainer.skype"}}'}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
