# Path to your oh-my-zsh installation.
export ZSH=/home/piontec/.oh-my-zsh

export WORKON_HOME=$HOME/.virtualenvs

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="muse"
ZSH_THEME="risto"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  autojump
  aws 
  common-aliases
  copyfile
  dircycle
  docker
  fzf-tab
  git
  gitfast
  httpie
  kube-ps1
  kubectl 
  pass
  pip
  poetry
  sudo 
  systemd
  terraform
  tmux
  zsh-autosuggestions
)

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# User configuration
export GOPATH=~/devel/go
export GOROOT=/usr/lib/go

export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/bin/:$GOROOT/bin:$GOPATH/bin:/snap/bin"
# export MANPATH="/usr/local/man:$MANPATH"
export TF_PLUGIN_CACHE_DIR=/opt/terraform-plugin-dir

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

PROMPT=$PROMPT'$(kube_ps1) '
KUBE_PS1_NS_ENABLE=false
KUBE_PS1_SYMBOL_USE_IMG=true
KUBE_PS1_DIVIDER=''

# pyenv setup
export PYENV_ROOT=$HOME/tools/pyenv
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# rust
export PATH="$HOME/.cargo/bin:$PATH"

#poetry
# Compilation flags
# export ARCHFLAGS="-arch x86_64"

#krew
export PATH="$PATH:${HOME}/.krew/bin"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias watch="watch "
alias slackutil="docker run --rm -ti -e SLACK_TOKEN=${SLACK_TOKEN} quay.io/giantswarm/slackutil"
alias cat="batcat -p"
alias tf=terraform-0.12
alias tf12=terraform-0.12
alias tf11=terraform
alias k=kubectl
alias kctx="kubectl ctx"
alias ks="kubectl -n kube-system"
alias kg="kubectl -n giantswarm"
alias km="kubectl -n monitoring"
alias kn="kubectl neat"
alias open=xdg-open
alias opsctl='OPSCTL_OPSGENIE_TOKEN=`lpass show --notes dev/OPSCTL_OPSGENIE_TOKEN` OPSCTL_GPG_PASSWORD=`lpass show --notes "Shared-Dev Common/opsctl GPG password" | cut -f2 -d"=" | tr -d \"` OPSCTL_GITHUB_TOKEN=`lpass show --password dev/github_private_token` PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $HOME/bin/opsctl'
alias dopsctl='docker run --network host --dns 10.0.253.1 -v ~/.kube/:/home/piontec/.kube/ -v ~/.config/:/home/piontec/.config/ -e OPSCTL_OPSGENIE_TOKEN=`lpass show --notes dev/OPSCTL_OPSGENIE_TOKEN` -e OPSCTL_GPG_PASSWORD=`lpass show --notes "Shared-Dev Common/opsctl GPG password" | cut -f2 -d"=" | tr -d \"` -e OPSCTL_GITHUB_TOKEN=`lpass show --password dev/github_private_token` gs_utils:latest opsctl'
alias dgsctl='docker run --network host --dns 10.0.253.1 -v ~/.kube/:/home/piontec/.kube/ -v ~/.config/:/home/piontec/.config/ gs_utils:latest gsctl'
alias gg="git graph"
alias gcrb="git branch -r | awk \"{print \\\$1}\" | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk \"{print \\\$1}\" | xargs git branch -D"
unalias cp
unalias rm

# exa
alias ls='exa'                                                          # ls
alias l='exa -lbF'                                                # list, size, type, git
alias ll='exa -lbGF'                                             # long list
alias llm='exa -lbGd  --sort=modified'                            # long list, modified date sort
alias la='exa -lbhHigUmuSa --time-style=long-iso --color-scale'  # all list
alias lx='exa -lbhHigUmuSa@ --time-style=long-iso --color-scale' # all + extended list
alias lS='exa -1'                                                              # one column, just names
alias lt='exa --tree --level=2'                                         # tree

# gs
 #: which kubeconfig 
kubeconfig ()
{ 
    if (( $# == 1 )); then
        kubectl gs login "$1";
    else
        if (( $# == 2 )); then
            kubectl gs login "$1" --certificate-group "system:masters" --certificate-ttl 24h --workload-cluster "$2";
        else
            if (( $# == 3 )); then
                kubectl gs login "$1" --certificate-group "system:masters" --certificate-ttl 24h --workload-cluster "$2" --organization "$3";
            else
                echo "Illegal number of parameters (installation [workload-cluster [organization]])" 1>&2;
            fi;
        fi;
    fi
}

# fzf
source /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export CHEAT_USE_FZF=true
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#666666,underline"

eval "$(starship init zsh)"
