#- name: update system with dist-upgrade
#  apt: update_cache=true cache_valid_time=3600 upgrade=dist

- name: Install base CLI dependencies
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - ntp
    - ntpdate 
    - openssh-server 
    - sudo 
    - vlan
    - vim-nox
    - htop
    - byobu
    - deborphan
    - git
    - apt-file
  register: cli_basics_installed
  notify:
    - Start NTP

