set nocompatible
let mapleader = ','
set hidden
" move between lines in editor, not lines in the file (line wraps)
nnoremap j gj
nnoremap k gk

" mv between windows
nnoremap <silent> <C-l> <c-w>l
nnoremap <silent> <C-h> <c-w>h
nnoremap <silent> <C-k> <c-w>k
nnoremap <silent> <C-j> <c-w>j

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
  Plugin 'gmarik/Vundle.vim'
  Plugin 'tpope/vim-fugitive'
  Plugin 'KabbAmine/zeavim.vim'
  Plugin 'bling/vim-airline'
  Plugin 'ekalinin/Dockerfile.vim'
  Plugin 'jlanzarotta/bufexplorer'
  Plugin 'scrooloose/nerdtree'
  Plugin 'scrooloose/nerdcommenter'
  Plugin 'kien/ctrlp.vim'
  Plugin 'mileszs/ack.vim'
  Plugin 'pearofducks/ansible-vim'
  Plugin 'altercation/vim-colors-solarized'
  Plugin 'airblade/vim-gitgutter'
  Plugin 'majutsushi/tagbar'
  " tabular always before vim-markdown
  Plugin 'godlygeek/tabular'
  Plugin 'plasticboy/vim-markdown'
  "  Plugin 'Shougo/neocomplete.vim' 
  Plugin 'Valloric/YouCompleteMe'
  Plugin 'elzr/vim-json'
  "  Plugin 'jiangmiao/auto-pairs'
  "  Plugin 'tpope/vim-surround'
  Plugin 'michaeljsmith/vim-indent-object'
  Plugin 'bkad/CamelCaseMotion'
  Plugin 'tomtom/tcomment_vim'
  Plugin 'hashivim/vim-terraform.git'
  Plugin 'fatih/vim-go'
  " Track the engine.
  Plugin 'SirVer/ultisnips'
  " Snippets are separated from the engine. Add this if you want them:
  Plugin 'honza/vim-snippets'
  " kube templates
  Plugin 'andrewstuart/vim-kubernetes'
  Plugin 'dbeniamine/cheat.sh-vim'
"  Plugin 'vim-scripts/ZoomWin'
  "  Plugin 'Valloric/YouetompleteMe'
"  Plugin 'LaTeX-Box-Team/LaTeX-Box'
  " Plugin 'derekwyatt/vim-scala'
  "Plugin 'junegunn/goyo.vim'
"  Plugin 'chriskempson/base16-vim'
"  Plugin 'liuchengxu/vim-better-default'
call vundle#end()
let g:go_version_warning = 0

runtime! plugin/default.vim
set norelativenumber

" python file handling
au BufNewFile,BufRead *.py set tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent fileformat=unix

" map camel case movement
"let g:vim_json_syntax_conceal = 0
"map <silent> w <Plug>CamelCaseMotion_w 
"map <silent> b <Plug>CamelCaseMotion_b 
map <silent> e <Plug>CamelCaseMotion_e 
map <silent> ge <Plug>CamelCaseMotion_ge 

" YCM
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>


syntax on
" error in < 7.4
if v:version > 704 
  set regexpengine=1
endif

nmap <silent> <F7> :NERDTreeToggle<CR>
nmap <silent> <F8> :TagbarToggle<CR>

" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" ack-vim
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" ulti-snips
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" markdown
let g:vim_markdown_folding_disabled = 1

" vim-aws
let g:AWSVimValidate = 1

set hlsearch
" tabs and firends
set autoindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
"set textwidth=100
set ignorecase 
set smartcase
set incsearch
set autochdir
" directory for swp files
set directory=/tmp
set wildmenu
set wildmode=longest,list
set showcmd
set showmatch
set pastetoggle=<F10>
set number
set iskeyword-=_
filetype plugin on
set grepprg=grep\ -nH\ $*
filetype indent on 
" set mouse in terminal to resize windows
"set mouse=a
set laststatus=2 

au BufNewFile,BufRead *.template set filetype=json


set background=dark
colorscheme solarized 

"GUI
"if has('gui_running')
"  set guioptions-=T  "remove toolbar
"  set guioptions-=r  "remove right-hand scroll bar
"else
"  let base16colorspace=256
"  set background=dark
"  colorscheme base16-solarized
"  " let g:solarized_termcolors=256
"  " set  background=light
"  " colorscheme solarized 
"endif
"
" au FileType tex set background=light | let g:solarized_termcolors=256 | colorscheme solarized 

cmap w!! %!sudo tee > /dev/null %
"tab navigation
"from Practical Vim book
"nnoremap <silent> <C-H> :bprev<CR> 
"nnoremap <silent> <C-L> :bnext<CR>
nnoremap <silent> [b :bprev<CR> 
nnoremap <silent> ]b :bnext<CR>
nnoremap <silent> [B :bfirst<CR>
nnoremap <silent> ]B :blast<CR>

" Reselect last pasted text
nnoremap gp `[v`]
" highlight search matching
" włączenie (zp) i wyłązenie (zP) korekty pisowni dla j.polskiego
map zp :setlocal spell spelllang=pl<CR>
map zP :setlocal nospell<CR>

" " włączenie (ze) i wyłączenie (zE) korekty pisowni dla j.angielskiego
map ze :setlocal spell spelllang=en<CR>
map zE :setlocal nospell<CR>
map zus :setlocal spell spelllang=en_us<CR>

if $TERM =~ '^screen-256color'
  map <Esc>OH <Home>
  map! <Esc>OH <Home>
  map <Esc>OF <End>
  map! <Esc>OF <End>
endif

fu! ToggleCurline ()
  if &cursorline && &cursorcolumn 
    set nocursorline
    set nocursorcolumn
  else
    set cursorline
    set cursorcolumn
  endif
endfunction

map <silent><leader>cl :call ToggleCurline()<CR>

imap jj <Esc>
" inoremap <C-Space> <C-n>
inoremap <Tab> <C-n>
inoremap <C-@> <C-Space>
nmap <C-_> <leader>c<Space>
nmap <C-f> :Ack<Space>
"nnoremap <S-CR> O<Esc>
"nnoremap <CR> o<Esc>
"map <Esc>OM <S-CR>

" Go
au FileType go nmap <Leader>s <Plug>(go-implements)
au FileType go nmap <Leader>i <Plug>(go-info)
" au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1

"mutt
"
au BufRead /tmp/mutt-* set tw=78 

" Airline
"
"let g:airline#extensions#tabline#enabled = 1
"let g:airline_theme = 'wombat'
"let g:airline#extensions#tabline#buffer_nr_show = 0

"terraform
let g:terraform_align=1

"Goyo
let g:goyo_width=100

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Code from:
" http://stackoverflow.com/questions/5585129/pasting-code-into-terminal-window-into-vim-on-mac-os-x
" then https://coderwall.com/p/if9mda
" and then https://github.com/aaronjensen/vimfiles/blob/59a7019b1f2d08c70c28a41ef4e2612470ea0549/plugin/terminaltweaks.vim
" to fix the escape time problem with insert mode.
"
" Docs on bracketed paste mode:
" http://www.xfree86.org/current/ctlseqs.html
" Docs on mapping fast escape codes in vim
" http://vim.wikia.com/wiki/Mapping_fast_keycodes_in_terminal_Vim

if !exists("g:bracketed_paste_tmux_wrap")
  let g:bracketed_paste_tmux_wrap = 1
endif

function! WrapForTmux(s)
  if !g:bracketed_paste_tmux_wrap || !exists('$TMUX')
    return a:s
  endif

  let tmux_start = "\<Esc>Ptmux;"
  let tmux_end = "\<Esc>\\"

  return tmux_start . substitute(a:s, "\<Esc>", "\<Esc>\<Esc>", 'g') . tmux_end
endfunction

let &t_SI .= WrapForTmux("\<Esc>[?2004h")
let &t_EI .= WrapForTmux("\<Esc>[?2004l")

function! XTermPasteBegin(ret)
  set pastetoggle=<f29>
  set paste
  return a:ret
endfunction

" auto paste mode
execute "set <f28>=\<Esc>[200~"
execute "set <f29>=\<Esc>[201~"
map <expr> <f28> XTermPasteBegin("i")
imap <expr> <f28> XTermPasteBegin("")
vmap <expr> <f28> XTermPasteBegin("c")
cmap <f28> <nop>
cmap <f29> <nop>

" virt env
"py << EOF
"import os
"import sys
"if 'VIRTUAL_ENV' in os.environ:
"  project_base_dir = os.environ['VIRTUAL_ENV']
"  activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
"  execfile(activate_this, dict(__file__=activate_this))
"EOF
