conf .defaults
mode strict
jail copilot
dir .cache/copilot/
dir .cargo/
dir .copilot/
dir gsd-workspaces/
rdir .agents/
rdir .config/github-copilot/
rdir .config/gh/
rdir .linuxbrew/
rdir .local/
rdir .oci/
rdir .rustup/
rdir bin/
setenv KUBECONFIG=${KUBECONFIG}
setenv PATH=${HOME}/bin:${PATH}
setenv DOCKER_BUILDKIT=0
setenv DOCKER_HOST=tcp://127.0.0.1:2375
