conf .defaults
mode strict
jail opencode
dir .cache/opencode
dir .local/share/opencode
dir .cargo/
dir devel/piontec-github/trdr
dir devel/piontec-github/trdr-wt
rdir .agents/
rdir .config/opencode/
rdir .linuxbrew/
rdir .local/
rdir .oci/
rdir .rustup/
rdir bin/
setenv KUBECONFIG=${KUBECONFIG}
setenv PATH=${HOME}/bin:${PATH}
setenv DOCKER_BUILDKIT=0
setenv DOCKER_HOST=tcp://127.0.0.1:2375
