- name: add VirtualBox key to apt sources
  apt_key: url="https://www.virtualbox.org/download/oracle_vbox.asc" state=present

- name: add VirtualBox to apt sources
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib" state=present

- name: add docker key to apt sources
  apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id="58118E89F3A912897C070ADBF76221572C52609D" state=present

- name: add docker to apt sources
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_lsb.codename }} main" state=present

- name: Install packages
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - linux-image-extra-virtual
    - virt-manager
    - dkms
    - virtualbox-5.0
    - docker-engine
